name = "out-of-tree preload"
type = "module"

[[supported_kernels]]
distro = { id = "Ubuntu", release = "18.04" }
release_mask = ".*"

[[preload]]
repo = "https://github.com/openwall/lkrg"
#path = "/local/path/to/lkrg"
timeout_after_load = "1s"
