name = "preload_example"
type = "module"

[[targets]]
distro = { id = "Ubuntu", release = "18.04" }
kernel = { regex = ".*" }

[[preload]]
repo = "https://github.com/openwall/lkrg"
#path = "/local/path/to/lkrg"
timeout_after_load = "1s"
