# out-of-tree configuration file
# docs at https://out-of-tree.io
name = "out-of-tree module example"
type = "module"

[[targets]]
# Can be Ubuntu/CentOS/Debian/etc.
distro = { id = "Ubuntu", release = "16.04" }
# regex for `uname -r`
# See also: regex-golang.appspot.com
kernel = { regex = "4[.]4[.]0-70-.*" }

# [[targets]] may be defined unlimited number of times
[[targets]]
distro = { id = "Ubuntu", release = "18.04" }
# Also you can use only one kernel
kernel = { regex = "4[.]15[.]0-(24|29)-generic" }

[[targets]]
distro = { id = "Ubuntu", release = "18.04" }
# Also you can use only one kernel
kernel = { regex = "4[.]15[.]0-23-generic" }

[[targets]]
distro = { id = "CentOS", release = "7" }
kernel = { regex = "3[.]10[.]0-862.el7.x86_64" }
