# out-of-tree configuration file
# docs at https://out-of-tree.io
name = "out-of-tree script example"
type = "script"

script = "script.sh"

[[supported_kernels]]
distro = { id = "Ubuntu", release = "22.04" }
release_mask = ".*"
