name: Debian

on:
  workflow_dispatch:
  schedule:
    - cron: '45 0 * * 5'

jobs:
  debian-cache:
    name: Build Cache
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: go build

    - name: Cache
      run: ./out-of-tree --log-level=trace debian cache --path=/home/runner/debian.cache

    - name: Archive cache
      uses: actions/upload-artifact@v3
      with:
        name: debian-cache
        path: /home/runner/debian.cache

    - name: Upload cache
      uses: BetaHuhn/do-spaces-action@v2
      with:
        access_key: ${{ secrets.ACCESS_KEY }}
        secret_key: ${{ secrets.SECRET_KEY }}
        space_name: ${{ secrets.SPACE_NAME }}
        space_region: ${{ secrets.SPACE_REGION }}
        source: /home/runner/debian.cache
        out_dir: 1.0.0

    - name: Archive logs
      uses: actions/upload-artifact@v3
      with:
        name: debian-cache-logs
        path: /home/runner/.out-of-tree/logs
