name: Debian

on:
  workflow_dispatch:
  schedule:
    - cron: '45 0 * * 5'

jobs:
  debian-cache:
    name: Build Cache
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: go build

    - name: Cache
      run: ./out-of-tree --log-level=trace debian cache --path=/home/runner/debian.cache

    - name: Install s3cmd
      run: sudo apt install s3cmd

    - name: Upload cache
      run: s3cmd put /home/runner/debian.cache s3://out-of-tree/1.0.0 --host=fra1.digitaloceanspaces.com --access_key=${{ secrets.DIGITALOCEAN_SPACES_ACCESS_KEY }} --secret_key=${{ secrets.DIGITALOCEAN_SPACES_SECRET_KEY }}

    - name: Archive cache
      uses: actions/upload-artifact@v3
      with:
        name: debian-cache
        path: /home/runner/debian.cache

    - name: Archive logs
      uses: actions/upload-artifact@v3
      with:
        name: debian-cache-logs
        path: /home/runner/.out-of-tree/logs
