name: Debian images

on:
  workflow_dispatch:
  push:
    paths:
      - 'tools/qemu-debian-img/**'
      - '.github/workflows/images-debian.yml'

jobs:
  images:
    name: Generate Debian images
    runs-on: ubuntu-latest
    steps:
    - uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: create droplet
      run: doctl compute droplet create --ssh-keys='b4:4c:66:7d:be:19:25:43:1c:e0:02:61:9f:49:12:94' --tag-name=github-actions ga-out-of-tree-images-debian-$GITHUB_SHA --size s-1vcpu-1gb --image ubuntu-22-04-x64 --wait

    - name: generate images
      shell: bash
      run: |
        IP=$(doctl compute droplet list --tag-name=github-actions --format "Name,Public IPv4" | grep -v ID | grep ga-out-of-tree-images-debian-$GITHUB_SHA | awk '{print $2}')

        while ! ssh -o StrictHostKeyChecking=accept-new root@$IP echo
        do
          sleep 1s
        done

        sleep 1m
        ssh root@$IP pkill apt-get

        ssh root@$IP apt-get update
        ssh root@$IP apt-get install -y git podman s3cmd
        ssh root@$IP git clone https://github.com/out-of-tree/out-of-tree
        ssh root@$IP "cd out-of-tree && git checkout $GITHUB_SHA"

        ssh root@$IP "echo -e '[Unit]\nDescription=Debian image generator and uploader\n[Service]\nStandardError=append:/var/log/images-debian.log\nStandardOutput=append:/var/log/images-debian.log\nType=oneshot' >> /etc/systemd/system/images-debian.service"

        ssh root@$IP "echo Environment=HOST=fra1.digitaloceanspaces.com >> /etc/systemd/system/images-debian.service"
        ssh root@$IP "echo Environment=HOST_BUCKET=out-of-tree.fra1.digitaloceanspaces.com >> /etc/systemd/system/images-debian.service"
        ssh root@$IP "echo Environment=ACCESS_KEY=${{ secrets.DIGITALOCEAN_SPACES_ACCESS_KEY }} >> /etc/systemd/system/images-debian.service"
        ssh root@$IP "echo Environment=SECRET_KEY=${{ secrets.DIGITALOCEAN_SPACES_SECRET_KEY }} >> /etc/systemd/system/images-debian.service"

        ssh root@$IP "echo 'ExecStart=/root/out-of-tree/tools/qemu-debian-img/generate-images.sh' >> /etc/systemd/system/images-debian.service"

        ssh root@$IP 'echo ExecStart=/bin/sh -c \"s3cmd put --acl-public /root/out-of-tree/tools/qemu-debian-img/*.tar.gz s3://out-of-tree/1.0.0/ --host=\$HOST --host-bucket=\$HOST_BUCKET --access_key=\$ACCESS_KEY --secret_key=\$SECRET_KEY\" >> /etc/systemd/system/images-debian.service'

        ssh root@$IP "echo TimeoutStopSec=1 >> /etc/systemd/system/images-debian.service"

        ssh root@$IP systemctl daemon-reload

        ssh root@$IP systemctl start images-debian --no-block

        ssh root@$IP systemctl status images-debian
        while [[ $? == 3 ]]; do
          sleep 1s
          ssh root@$IP systemctl status images-debian
        done

        scp root@$IP:/var/log/images-debian.log .

    - name: Archive logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: images-debian-log
        path: images-debian.log

    - name: delete droplet
      if: always()
      run: doctl compute droplet delete -f ga-out-of-tree-images-debian-$GITHUB_SHA
