name: Build on macOS

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - ".github/workflows/images-*"
      - ".github/workflows/debian-cache.yml"
  pull_request:

jobs:
  build:
    name: Build on macOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: go build
