name: macOS

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - ".github/workflows/images-*"
      - ".github/workflows/debian-cache.yml"
      - ".github/workflows/e2e.yml"
      - "docs/**"
      - "README.md"
  pull_request:

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: go build
